### ISSUE TITLE
TagGUI Support

### ISSUE THREAD

**Issue by maedtb** [fpgaminer/joycaption#7]
Hi, I'm interested in using this model with TagGUI.  I wanted to start a thread here to run it by you before I went and added support in my own fork, in case this is something someone has already done, or if there was a good reason not to do so.

p.s. is there a place for news/announcements/etc to help keep track of the tooling projects (like joycaption) you've been working on while developing bigAsp?  Tooling is an area I think is highly, highly underdeveloped in this moving-too-fast field, and I think there may be a lot of low-hanging fruit.  I'd love to help contribute in this area as time allows.

**Comment by fpgaminer** [comment]
I'm always happy to see my models get integrated into other projects, so please feel free!  I'm not personally aware of any work for TagGUI specifically, but I also haven't been keeping track.

I tend to post articles and updates on civit (https://civitai.com/user/nutbutter/articles), code related updates can be followed on github, and new models and data end up on HF https://huggingface.co/fancyfeast.
